name: 'Protoc action'
description: 'Action for generate from client and server from protofiles'
author: 'PxyUp'
inputs:
  path:
    description: 'Path and arguments for protoc'
    required: true
outputs:
  success: # id of output
    description: 'Success'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
branding:
  icon: 'aperture'
  color: 'green'
